In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('usedready.csv')

In [3]:
df

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,Honda City 1.3 i-VTEC Prosmatec 2016,PKR 34.25 lacs,Sedan,1300 cc,Automatic,NaN,"89,000 km"
1,Honda Civic VTi Oriel 1.8 i-VTEC 2014,PKR 38 lacs,Sedan,1800 cc,NaN,NaN,"186,634 km"
2,Toyota Aqua S 2014,PKR 35.25 lacs,Hatchback,1500 cc,Automatic,NaN,"98,000 km"
3,Suzuki Bolan 2007,PKR 6.3 lacs,NaN,800 cc,NaN,NaN,80 km
4,Toyota Corolla GLi 1.3 VVTi 2012,PKR 26.5 lacs,Sedan,1300 cc,NaN,NaN,"170,000 km"
...,...,...,...,...,...,...,...
58,KIA Picanto 1.0 AT 2020,PKR 28.5 lacs,Hatchback,998 cc,Automatic,NaN,"57,000 km"
59,Honda Civic Oriel 1.8 i-VTEC CVT 2020,Call for price,Sedan,1800 cc,Automatic,NaN,"37,000 km"
60,Toyota Fortuner 2.7 VVTi 2013,PKR 72 lacs,SUV,2700 cc,Automatic,NaN,"137,000 km"
61,MG HS Trophy 2022,Call for price,Crossover,1500 cc,Automatic,NaN,"33,800 km"
62,Toyota Fortuner 2.8 Sigma 4 2021,Call for price,SUV,2800 cc,Automatic,NaN,"34,000 km"

In [4]:
data = df

In [5]:
data

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,Honda City 1.3 i-VTEC Prosmatec 2016,PKR 34.25 lacs,Sedan,1300 cc,Automatic,NaN,"89,000 km"
1,Honda Civic VTi Oriel 1.8 i-VTEC 2014,PKR 38 lacs,Sedan,1800 cc,NaN,NaN,"186,634 km"
2,Toyota Aqua S 2014,PKR 35.25 lacs,Hatchback,1500 cc,Automatic,NaN,"98,000 km"
3,Suzuki Bolan 2007,PKR 6.3 lacs,NaN,800 cc,NaN,NaN,80 km
4,Toyota Corolla GLi 1.3 VVTi 2012,PKR 26.5 lacs,Sedan,1300 cc,NaN,NaN,"170,000 km"
...,...,...,...,...,...,...,...
58,KIA Picanto 1.0 AT 2020,PKR 28.5 lacs,Hatchback,998 cc,Automatic,NaN,"57,000 km"
59,Honda Civic Oriel 1.8 i-VTEC CVT 2020,Call for price,Sedan,1800 cc,Automatic,NaN,"37,000 km"
60,Toyota Fortuner 2.7 VVTi 2013,PKR 72 lacs,SUV,2700 cc,Automatic,NaN,"137,000 km"
61,MG HS Trophy 2022,Call for price,Crossover,1500 cc,Automatic,NaN,"33,800 km"
62,Toyota Fortuner 2.8 Sigma 4 2021,Call for price,SUV,2800 cc,Automatic,NaN,"34,000 km"

In [6]:
# Remove the 'PKR' and 'lacs' from the Price column and handle rows with 'Call for price'
data['Price'] = data['Price'].str.replace('PKR ', '').str.replace(' lacs', '')
data = data[data['Price'] != 'Call for price']

# Convert cleaned price data to float, assuming 'lacs' means 'hundred thousands'
data['Price'] = data['Price'].astype(float) * 100000

# Show the cleaned data
cleaned_data_preview = data.head()
cleaned_data_preview

/var/folders/qq/825c9lpx42x0rhxk9smb4c8h0000gq/T/ipykernel_15394/2552331315.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Price'] = data['Price'].astype(float) * 100000

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,Honda City 1.3 i-VTEC Prosmatec 2016,3425000.0,Sedan,1300 cc,Automatic,NaN,"89,000 km"
1,Honda Civic VTi Oriel 1.8 i-VTEC 2014,3800000.0,Sedan,1800 cc,NaN,NaN,"186,634 km"
2,Toyota Aqua S 2014,3525000.0,Hatchback,1500 cc,Automatic,NaN,"98,000 km"
3,Suzuki Bolan 2007,630000.0,NaN,800 cc,NaN,NaN,80 km
4,Toyota Corolla GLi 1.3 VVTi 2012,2650000.0,Sedan,1300 cc,NaN,NaN,"170,000 km"

In [7]:
# Remove 'cc' from the Displacement column and convert to integer type
data['Displacement'] = data['Displacement'].str.replace(' cc', '').astype(float)

# Show the cleaned data
cleaned_displacement_data_preview = data.head()
cleaned_displacement_data_preview

/var/folders/qq/825c9lpx42x0rhxk9smb4c8h0000gq/T/ipykernel_15394/2369430077.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Displacement'] = data['Displacement'].str.replace(' cc', '').astype(float)

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,Honda City 1.3 i-VTEC Prosmatec 2016,3425000.0,Sedan,1300.0,Automatic,NaN,"89,000 km"
1,Honda Civic VTi Oriel 1.8 i-VTEC 2014,3800000.0,Sedan,1800.0,NaN,NaN,"186,634 km"
2,Toyota Aqua S 2014,3525000.0,Hatchback,1500.0,Automatic,NaN,"98,000 km"
3,Suzuki Bolan 2007,630000.0,NaN,800.0,NaN,NaN,80 km
4,Toyota Corolla GLi 1.3 VVTi 2012,2650000.0,Sedan,1300.0,NaN,NaN,"170,000 km"

In [8]:
# Remove 'km' from the Odometer column and convert to integer type
data['Odometer'] = data['Odometer'].str.replace(' km', '').str.replace(',', '').astype(int)

# Show the cleaned data
cleaned_odometer_data_preview = data.head()
cleaned_odometer_data_preview

/var/folders/qq/825c9lpx42x0rhxk9smb4c8h0000gq/T/ipykernel_15394/2766230448.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Odometer'] = data['Odometer'].str.replace(' km', '').str.replace(',', '').astype(int)

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,Honda City 1.3 i-VTEC Prosmatec 2016,3425000.0,Sedan,1300.0,Automatic,NaN,89000
1,Honda Civic VTi Oriel 1.8 i-VTEC 2014,3800000.0,Sedan,1800.0,NaN,NaN,186634
2,Toyota Aqua S 2014,3525000.0,Hatchback,1500.0,Automatic,NaN,98000
3,Suzuki Bolan 2007,630000.0,NaN,800.0,NaN,NaN,80
4,Toyota Corolla GLi 1.3 VVTi 2012,2650000.0,Sedan,1300.0,NaN,NaN,170000

In [12]:
# Replace NaN values in the 'Transmission' column with 'Manual'
data['Transmission'] = data['Transmission'].fillna('Manual')

data

/var/folders/qq/825c9lpx42x0rhxk9smb4c8h0000gq/T/ipykernel_15394/630402667.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Transmission'] = data['Transmission'].fillna('Manual')

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,Honda City 1.3 i-VTEC Prosmatec 2016,3425000.0,Sedan,1300.0,Automatic,NaN,89000
1,Honda Civic VTi Oriel 1.8 i-VTEC 2014,3800000.0,Sedan,1800.0,Manual,NaN,186634
2,Toyota Aqua S 2014,3525000.0,Hatchback,1500.0,Automatic,NaN,98000
3,Suzuki Bolan 2007,630000.0,NaN,800.0,Manual,NaN,80
4,Toyota Corolla GLi 1.3 VVTi 2012,2650000.0,Sedan,1300.0,Manual,NaN,170000
5,Toyota Corolla 1986,750000.0,NaN,1300.0,Manual,NaN,290000
6,Hyundai Sonata 2.0 2022,9000000.0,Sedan,2000.0,Automatic,NaN,31500
7,Suzuki Every PA 2008,1550000.0,Micro Van,660.0,Automatic,NaN,133000
8,Toyota Corolla Altis Grande CVT-i 1.8 2018,5700000.0,Sedan,1800.0,Automatic,NaN,73000
9,Suzuki Alto 2009,650000.0,NaN,800.0,Manual,NaN,11000
10,Suzuki Cultus VXL 2006,790000.0,Hatchback,1000.0,Manual,NaN,70000
11,Suzuki Alto VXL AGS 2021,2700000.0,Hatchback,660.0,Automatic,NaN,41000
12,Honda Civic VTi 1.6 2002,1620000.0,Sedan,1600.0,Manual,NaN,185445
13,Suzuki Ravi Euro II 2017,1280000.0,Pick Up,800.0,Manual,NaN,70000
14,Suzuki Mehran VX 2008,650000.0,Hatchback,800.0,Manual,NaN,150000
15,Suzuki Baleno Sport 2005,1300000.0,Sedan,1300.0,Manual,NaN,200000
16,Toyota Yaris GLI CVT 1.3 2021,4140000.0,Sedan,1300.0,Automatic,NaN,33414
17,Daihatsu Hijet Special 2008,1450000.0,Mini Van,660.0,Automatic,NaN,240000
18,Hyundai Santro Exec GV 2004,1040000.0,Hatchback,1000.0,Manual,NaN,360000
19,Honda Civic Oriel 1.8 i-VTEC CVT 2018,5375000.0,Sedan,1800.0,Automatic,NaN,127
20,Toyota Yaris ATIV MT 1.3 2021,4150000.0,Sedan,1300.0,Manual,NaN,15104
21,Toyota Corolla GLi 1.3 VVTi 2017,4500000.0,Sedan,1300.0,Manual,NaN,33500
22,Subaru Stella G 2015,2400000.0,Hatchback,660.0,Automatic,NaN,91000
23,Honda City 1.3 i-VTEC 2018,3425000.0,Sedan,1300.0,Manual,NaN,58000
24,Daihatsu Mira G SA III 2017,2850000.0,Hatchback,660.0,Automatic,NaN,74000
25,Toyota Voxy X 2014,5400000.0,Mini Van,2000.0,Automatic,NaN,72000
28,KIA Picanto 1.0 AT 2020,2850000.0,Hatchback,998.0,Automatic,NaN,57000
30,Suzuki Alto 2009,650000.0,NaN,800.0,Manual,NaN,11000
31,Suzuki Cultus VXL 2006,790000.0,Hatchback,1000.0,Manual,NaN,70000
32,Suzuki Alto VXL AGS 2021,2700000.0,Hatchback,660.0,Automatic,NaN,41000
33,Honda Civic VTi 1.6 2002,1620000.0,Sedan,1600.0,Manual,NaN,185445
34,Suzuki Ravi Euro II 2017,1280000.0,Pick Up,800.0,Manual,NaN,70000
35,Suzuki Mehran VX 2008,650000.0,Hatchback,800.0,Manual,NaN,150000
36,Suzuki Baleno Sport 2005,1300000.0,Sedan,1300.0,Manual,NaN,200000
37,Toyota Yaris GLI CVT 1.3 2021,4140000.0,Sedan,1300.0,Automatic,NaN,33414
38,Daihatsu Hijet Special 2008,1450000.0,Mini Van,660.0,Automatic,NaN,240000
39,Hyundai Elantra GLS 2022,6400000.0,Sedan,2000.0,Automatic,NaN,8200
40,Daihatsu Cuore CX Automatic 2006,820000.0,Hatchback,800.0,Automatic,NaN,115000
41,Toyota Aqua S 2017,4899000.0,Hatchback,1500.0,Automatic,NaN,85000
42,Suzuki Alto 2022,4025000.0,NaN,660.0,Automatic,NaN,12000
43,Honda City i-DSI 2007,1750000.0,Sedan,1300.0,Manual,NaN,170000
44,Toyota Hilux 1992,1600000.0,NaN,2000.0,Manual,NaN,150000
45,Honda Civic EXi Prosmatec 2004,1540000.0,Sedan,1500.0,Automatic,NaN,373124
46,Toyota Vitz 2011,2700000.0,NaN,1000.0,Automatic,NaN,180000
47,Honda Civic EXi Prosmatec 2003,1510000.0,Sedan,1500.0,Automatic,NaN,1
48,Honda City 1.3 i-VTEC Prosmatec 2018,3490000.0,Sedan,1300.0,Automatic,NaN,82000
49,Daihatsu Mira L SA 2014,2180000.0,Hatchback,660.0,Automatic,NaN,77000
50,Suzuki Liana LXi Sport 2007,1100000.0,Sedan,1300.0,Manual,NaN,118000
51,Honda Civic Oriel 1.8 i-VTEC CVT 2018,5375000.0,Sedan,1800.0,Automatic,NaN,127
52,Toyota Yaris ATIV MT 1.3 2021,4150000.0,Sedan,1300.0,Manual,NaN,15104
53,Toyota Corolla GLi 1.3 VVTi 2017,4500000.0,Sedan,1300.0,Manual,NaN,33500
54,Subaru Stella G 2015,2400000.0,Hatchback,660.0,Automatic,NaN,91000
55,Honda City 1.3 i-VTEC 2018,3425000.0,Sedan,1300.0,Manual,NaN,58000
56,Daihatsu Mira G SA III 2017,2850000.0,Hatchback,660.0,Automatic,NaN,74000
57,Toyota Voxy X 2014,5400000.0,Mini Van,2000.0,Automatic,NaN,72000
58,KIA Picanto 1.0 AT 2020,2850000.0,Hatchback,998.0,Automatic,NaN,57000
60,Toyota Fortuner 2.7 VVTi 2013,7200000.0,SUV,2700.0,Automatic,NaN,137000

In [13]:
# Replace NaN values in the 'Body Type' column with 'Hatchback'
data['Body Type'] = data['Body Type'].fillna('Hatchback')

# Show the updated data
updated_body_type_data_preview = data.head()
updated_body_type_data_preview

/var/folders/qq/825c9lpx42x0rhxk9smb4c8h0000gq/T/ipykernel_15394/3428695773.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Body Type'] = data['Body Type'].fillna('Hatchback')

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,Honda City 1.3 i-VTEC Prosmatec 2016,3425000.0,Sedan,1300.0,Automatic,NaN,89000
1,Honda Civic VTi Oriel 1.8 i-VTEC 2014,3800000.0,Sedan,1800.0,Manual,NaN,186634
2,Toyota Aqua S 2014,3525000.0,Hatchback,1500.0,Automatic,NaN,98000
3,Suzuki Bolan 2007,630000.0,Hatchback,800.0,Manual,NaN,80
4,Toyota Corolla GLi 1.3 VVTi 2012,2650000.0,Sedan,1300.0,Manual,NaN,170000

In [14]:
data

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,Honda City 1.3 i-VTEC Prosmatec 2016,3425000.0,Sedan,1300.0,Automatic,NaN,89000
1,Honda Civic VTi Oriel 1.8 i-VTEC 2014,3800000.0,Sedan,1800.0,Manual,NaN,186634
2,Toyota Aqua S 2014,3525000.0,Hatchback,1500.0,Automatic,NaN,98000
3,Suzuki Bolan 2007,630000.0,Hatchback,800.0,Manual,NaN,80
4,Toyota Corolla GLi 1.3 VVTi 2012,2650000.0,Sedan,1300.0,Manual,NaN,170000
5,Toyota Corolla 1986,750000.0,Hatchback,1300.0,Manual,NaN,290000
6,Hyundai Sonata 2.0 2022,9000000.0,Sedan,2000.0,Automatic,NaN,31500
7,Suzuki Every PA 2008,1550000.0,Micro Van,660.0,Automatic,NaN,133000
8,Toyota Corolla Altis Grande CVT-i 1.8 2018,5700000.0,Sedan,1800.0,Automatic,NaN,73000
9,Suzuki Alto 2009,650000.0,Hatchback,800.0,Manual,NaN,11000
10,Suzuki Cultus VXL 2006,790000.0,Hatchback,1000.0,Manual,NaN,70000
11,Suzuki Alto VXL AGS 2021,2700000.0,Hatchback,660.0,Automatic,NaN,41000
12,Honda Civic VTi 1.6 2002,1620000.0,Sedan,1600.0,Manual,NaN,185445
13,Suzuki Ravi Euro II 2017,1280000.0,Pick Up,800.0,Manual,NaN,70000
14,Suzuki Mehran VX 2008,650000.0,Hatchback,800.0,Manual,NaN,150000
15,Suzuki Baleno Sport 2005,1300000.0,Sedan,1300.0,Manual,NaN,200000
16,Toyota Yaris GLI CVT 1.3 2021,4140000.0,Sedan,1300.0,Automatic,NaN,33414
17,Daihatsu Hijet Special 2008,1450000.0,Mini Van,660.0,Automatic,NaN,240000
18,Hyundai Santro Exec GV 2004,1040000.0,Hatchback,1000.0,Manual,NaN,360000
19,Honda Civic Oriel 1.8 i-VTEC CVT 2018,5375000.0,Sedan,1800.0,Automatic,NaN,127
20,Toyota Yaris ATIV MT 1.3 2021,4150000.0,Sedan,1300.0,Manual,NaN,15104
21,Toyota Corolla GLi 1.3 VVTi 2017,4500000.0,Sedan,1300.0,Manual,NaN,33500
22,Subaru Stella G 2015,2400000.0,Hatchback,660.0,Automatic,NaN,91000
23,Honda City 1.3 i-VTEC 2018,3425000.0,Sedan,1300.0,Manual,NaN,58000
24,Daihatsu Mira G SA III 2017,2850000.0,Hatchback,660.0,Automatic,NaN,74000
25,Toyota Voxy X 2014,5400000.0,Mini Van,2000.0,Automatic,NaN,72000
28,KIA Picanto 1.0 AT 2020,2850000.0,Hatchback,998.0,Automatic,NaN,57000
30,Suzuki Alto 2009,650000.0,Hatchback,800.0,Manual,NaN,11000
31,Suzuki Cultus VXL 2006,790000.0,Hatchback,1000.0,Manual,NaN,70000
32,Suzuki Alto VXL AGS 2021,2700000.0,Hatchback,660.0,Automatic,NaN,41000
33,Honda Civic VTi 1.6 2002,1620000.0,Sedan,1600.0,Manual,NaN,185445
34,Suzuki Ravi Euro II 2017,1280000.0,Pick Up,800.0,Manual,NaN,70000
35,Suzuki Mehran VX 2008,650000.0,Hatchback,800.0,Manual,NaN,150000
36,Suzuki Baleno Sport 2005,1300000.0,Sedan,1300.0,Manual,NaN,200000
37,Toyota Yaris GLI CVT 1.3 2021,4140000.0,Sedan,1300.0,Automatic,NaN,33414
38,Daihatsu Hijet Special 2008,1450000.0,Mini Van,660.0,Automatic,NaN,240000
39,Hyundai Elantra GLS 2022,6400000.0,Sedan,2000.0,Automatic,NaN,8200
40,Daihatsu Cuore CX Automatic 2006,820000.0,Hatchback,800.0,Automatic,NaN,115000
41,Toyota Aqua S 2017,4899000.0,Hatchback,1500.0,Automatic,NaN,85000
42,Suzuki Alto 2022,4025000.0,Hatchback,660.0,Automatic,NaN,12000
43,Honda City i-DSI 2007,1750000.0,Sedan,1300.0,Manual,NaN,170000
44,Toyota Hilux 1992,1600000.0,Hatchback,2000.0,Manual,NaN,150000
45,Honda Civic EXi Prosmatec 2004,1540000.0,Sedan,1500.0,Automatic,NaN,373124
46,Toyota Vitz 2011,2700000.0,Hatchback,1000.0,Automatic,NaN,180000
47,Honda Civic EXi Prosmatec 2003,1510000.0,Sedan,1500.0,Automatic,NaN,1
48,Honda City 1.3 i-VTEC Prosmatec 2018,3490000.0,Sedan,1300.0,Automatic,NaN,82000
49,Daihatsu Mira L SA 2014,2180000.0,Hatchback,660.0,Automatic,NaN,77000
50,Suzuki Liana LXi Sport 2007,1100000.0,Sedan,1300.0,Manual,NaN,118000
51,Honda Civic Oriel 1.8 i-VTEC CVT 2018,5375000.0,Sedan,1800.0,Automatic,NaN,127
52,Toyota Yaris ATIV MT 1.3 2021,4150000.0,Sedan,1300.0,Manual,NaN,15104
53,Toyota Corolla GLi 1.3 VVTi 2017,4500000.0,Sedan,1300.0,Manual,NaN,33500
54,Subaru Stella G 2015,2400000.0,Hatchback,660.0,Automatic,NaN,91000
55,Honda City 1.3 i-VTEC 2018,3425000.0,Sedan,1300.0,Manual,NaN,58000
56,Daihatsu Mira G SA III 2017,2850000.0,Hatchback,660.0,Automatic,NaN,74000
57,Toyota Voxy X 2014,5400000.0,Mini Van,2000.0,Automatic,NaN,72000
58,KIA Picanto 1.0 AT 2020,2850000.0,Hatchback,998.0,Automatic,NaN,57000
60,Toyota Fortuner 2.7 VVTi 2013,7200000.0,SUV,2700.0,Automatic,NaN,137000

In [17]:
import numpy as np

# Randomly fill NaN values in 'Seating Capacity' with 5 or 7, with 5 being more frequent
np.random.seed(42)  # For reproducibility
data['Seating Capacity'] = data['Seating Capacity'].apply(
    lambda x: np.random.choice([5, 7], p=[0.95, 0.05]) if pd.isna(x) else x
)

# Show the updated data
updated_seating_capacity_data_preview = data.head()
updated_seating_capacity_data_preview

/var/folders/qq/825c9lpx42x0rhxk9smb4c8h0000gq/T/ipykernel_15394/702497352.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Seating Capacity'] = data['Seating Capacity'].apply(

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,Honda City 1.3 i-VTEC Prosmatec 2016,3425000.0,Sedan,1300.0,Automatic,5,89000
1,Honda Civic VTi Oriel 1.8 i-VTEC 2014,3800000.0,Sedan,1800.0,Manual,7,186634
2,Toyota Aqua S 2014,3525000.0,Hatchback,1500.0,Automatic,5,98000
3,Suzuki Bolan 2007,630000.0,Hatchback,800.0,Manual,5,80
4,Toyota Corolla GLi 1.3 VVTi 2012,2650000.0,Sedan,1300.0,Manual,5,170000

In [18]:
data

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,Honda City 1.3 i-VTEC Prosmatec 2016,3425000.0,Sedan,1300.0,Automatic,5,89000
1,Honda Civic VTi Oriel 1.8 i-VTEC 2014,3800000.0,Sedan,1800.0,Manual,7,186634
2,Toyota Aqua S 2014,3525000.0,Hatchback,1500.0,Automatic,5,98000
3,Suzuki Bolan 2007,630000.0,Hatchback,800.0,Manual,5,80
4,Toyota Corolla GLi 1.3 VVTi 2012,2650000.0,Sedan,1300.0,Manual,5,170000
5,Toyota Corolla 1986,750000.0,Hatchback,1300.0,Manual,5,290000
6,Hyundai Sonata 2.0 2022,9000000.0,Sedan,2000.0,Automatic,5,31500
7,Suzuki Every PA 2008,1550000.0,Micro Van,660.0,Automatic,5,133000
8,Toyota Corolla Altis Grande CVT-i 1.8 2018,5700000.0,Sedan,1800.0,Automatic,5,73000
9,Suzuki Alto 2009,650000.0,Hatchback,800.0,Manual,5,11000
10,Suzuki Cultus VXL 2006,790000.0,Hatchback,1000.0,Manual,5,70000
11,Suzuki Alto VXL AGS 2021,2700000.0,Hatchback,660.0,Automatic,7,41000
12,Honda Civic VTi 1.6 2002,1620000.0,Sedan,1600.0,Manual,5,185445
13,Suzuki Ravi Euro II 2017,1280000.0,Pick Up,800.0,Manual,5,70000
14,Suzuki Mehran VX 2008,650000.0,Hatchback,800.0,Manual,5,150000
15,Suzuki Baleno Sport 2005,1300000.0,Sedan,1300.0,Manual,5,200000
16,Toyota Yaris GLI CVT 1.3 2021,4140000.0,Sedan,1300.0,Automatic,5,33414
17,Daihatsu Hijet Special 2008,1450000.0,Mini Van,660.0,Automatic,5,240000
18,Hyundai Santro Exec GV 2004,1040000.0,Hatchback,1000.0,Manual,5,360000
19,Honda Civic Oriel 1.8 i-VTEC CVT 2018,5375000.0,Sedan,1800.0,Automatic,5,127
20,Toyota Yaris ATIV MT 1.3 2021,4150000.0,Sedan,1300.0,Manual,5,15104
21,Toyota Corolla GLi 1.3 VVTi 2017,4500000.0,Sedan,1300.0,Manual,5,33500
22,Subaru Stella G 2015,2400000.0,Hatchback,660.0,Automatic,5,91000
23,Honda City 1.3 i-VTEC 2018,3425000.0,Sedan,1300.0,Manual,5,58000
24,Daihatsu Mira G SA III 2017,2850000.0,Hatchback,660.0,Automatic,5,74000
25,Toyota Voxy X 2014,5400000.0,Mini Van,2000.0,Automatic,5,72000
28,KIA Picanto 1.0 AT 2020,2850000.0,Hatchback,998.0,Automatic,5,57000
30,Suzuki Alto 2009,650000.0,Hatchback,800.0,Manual,5,11000
31,Suzuki Cultus VXL 2006,790000.0,Hatchback,1000.0,Manual,5,70000
32,Suzuki Alto VXL AGS 2021,2700000.0,Hatchback,660.0,Automatic,5,41000
33,Honda Civic VTi 1.6 2002,1620000.0,Sedan,1600.0,Manual,5,185445
34,Suzuki Ravi Euro II 2017,1280000.0,Pick Up,800.0,Manual,5,70000
35,Suzuki Mehran VX 2008,650000.0,Hatchback,800.0,Manual,5,150000
36,Suzuki Baleno Sport 2005,1300000.0,Sedan,1300.0,Manual,7,200000
37,Toyota Yaris GLI CVT 1.3 2021,4140000.0,Sedan,1300.0,Automatic,7,33414
38,Daihatsu Hijet Special 2008,1450000.0,Mini Van,660.0,Automatic,5,240000
39,Hyundai Elantra GLS 2022,6400000.0,Sedan,2000.0,Automatic,5,8200
40,Daihatsu Cuore CX Automatic 2006,820000.0,Hatchback,800.0,Automatic,5,115000
41,Toyota Aqua S 2017,4899000.0,Hatchback,1500.0,Automatic,5,85000
42,Suzuki Alto 2022,4025000.0,Hatchback,660.0,Automatic,5,12000
43,Honda City i-DSI 2007,1750000.0,Sedan,1300.0,Manual,5,170000
44,Toyota Hilux 1992,1600000.0,Hatchback,2000.0,Manual,5,150000
45,Honda Civic EXi Prosmatec 2004,1540000.0,Sedan,1500.0,Automatic,5,373124
46,Toyota Vitz 2011,2700000.0,Hatchback,1000.0,Automatic,7,180000
47,Honda Civic EXi Prosmatec 2003,1510000.0,Sedan,1500.0,Automatic,5,1
48,Honda City 1.3 i-VTEC Prosmatec 2018,3490000.0,Sedan,1300.0,Automatic,5,82000
49,Daihatsu Mira L SA 2014,2180000.0,Hatchback,660.0,Automatic,5,77000
50,Suzuki Liana LXi Sport 2007,1100000.0,Sedan,1300.0,Manual,5,118000
51,Honda Civic Oriel 1.8 i-VTEC CVT 2018,5375000.0,Sedan,1800.0,Automatic,5,127
52,Toyota Yaris ATIV MT 1.3 2021,4150000.0,Sedan,1300.0,Manual,5,15104
53,Toyota Corolla GLi 1.3 VVTi 2017,4500000.0,Sedan,1300.0,Manual,7,33500
54,Subaru Stella G 2015,2400000.0,Hatchback,660.0,Automatic,5,91000
55,Honda City 1.3 i-VTEC 2018,3425000.0,Sedan,1300.0,Manual,7,58000
56,Daihatsu Mira G SA III 2017,2850000.0,Hatchback,660.0,Automatic,5,74000
57,Toyota Voxy X 2014,5400000.0,Mini Van,2000.0,Automatic,5,72000
58,KIA Picanto 1.0 AT 2020,2850000.0,Hatchback,998.0,Automatic,7,57000
60,Toyota Fortuner 2.7 VVTi 2013,7200000.0,SUV,2700.0,Automatic,5,137000

In [19]:
data.to_csv('ready_used.csv')

In [31]:
data = pd.read_csv('usednew.csv')

In [32]:
data

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,JW Forland Safari 2024 Specifications,35.0 - 43.0 lacs,MPV,1480 cc,Manual,7 - Persons,0
1,MG ZS EV 2024 Specifications,1.3 - 1.5 crore,Compact SUV,-,Automatic,5 - Persons,0
2,MG 4 2024 Specifications,1.1 - 1.3 crore,Crossover,-,Automatic,5 - Persons,0
3,Hyundai Santa Fe 2024 Specifications,1.3 - 1.47 crore,SUV,1598 cc,Automatic,7 - Persons,0
4,GUGO GIGI 2024 Specifications,46.5 lacs,Hatchback,-,Automatic,4 - Persons,0
5,Seres 3 2024 Specifications,83.9 lacs,SUV,-,Automatic,5 - Persons,0
6,MG 5 EV 2024 Specifications,1.35 crore,Station Wagon,-,Automatic,5 - Persons,0
7,Toyota Corolla Cross 2024 Specifications,82.0 - 98.5 lacs,SUV,1798 cc,Automatic,5 - Persons,0
8,ORA 03 2024 Specifications,90.0 lacs,Hatchback,-,Automatic,5 - Persons,0
9,Tank 500 2024 Specifications,4.5 crore,SUV,1998 cc,Automatic,7 - Persons,0
10,Hyundai Ioniq 6 2024 Specifications,2.3 crore,Compact sedan,-,Automatic,5 - Persons,0
11,Hyundai Ioniq 5 2024 Specifications,2.25 crore,SUV,-,Automatic,5 - Persons,0
12,Toyota Prado 2024 Specifications,-,SUV,2755 cc,Automatic,7 - Persons,0
13,Changan Karvaan 2024 Specifications,27.8 - 30.0 lacs,Mini Van,999 - 1243 cc,Manual,7 - Persons,0
14,MG HS 2024 Specifications,72.0 - 93.0 lacs,Crossover,1490 - 1995 cc,Automatic,5 - Persons,0
15,Hyundai Elantra 2024 Specifications,64.0 - 69.3 lacs,Sedan,1591 - 1999 cc,Automatic,5 - Persons,0
16,Hyundai Tucson 2024 Specifications,63.0 - 82.4 lacs,SUV,1999 cc,Automatic,5 - Persons,0
17,United Bravo 2024 Specifications,15.2 lacs,Hatchback,796 cc,Manual,5 - Persons,0
18,Prince Pearl 2024 Specifications,18.5 lacs,Hatchback,796 cc,Manual & Automatic,5 - Persons,0
19,Toyota Land Cruiser 2024 Specifications,12.0 crore,SUV,3444 - 3445 cc,Automatic,7 - Persons,0
20,Changan Alsvin 2024 Specifications,38.0 - 45.5 lacs,Sedan,1370 - 1480 cc,Manual & Automatic,5 - Persons,0
21,Honda BR-V 2024 Specifications,35.5 - 52.0 lacs,MPV,1497 cc,Automatic,7 - Persons,0
22,KIA Picanto 2024 Specifications,36.0 - 38.5 lacs,Hatchback,1000 cc,Manual & Automatic,5 - Persons,0
23,KIA Sportage 2024 Specifications,65.0 - 82.0 lacs,SUV,1999 cc,Automatic,5 - Persons,0
24,Toyota Fortuner 2024 Specifications,195.0 - 228.0 lacs,SUV,2694 - 2755 cc,Automatic,7 - Persons,0
25,Suzuki Swift 2024 Specifications,43.4 - 47.2 lacs,Hatchback,1200 cc,Manual & Automatic,5 - Persons,0
26,Toyota Yaris 2024 Specifications,43.3 - 58.5 lacs,Sedan,1329 - 1496 cc,Manual & Automatic,5 - Persons,0
27,Suzuki Wagon R 2024 Specifications,17.4 lacs,Hatchback,998 cc,Manual & Automatic,5 - Persons,0
28,Suzuki Cultus 2024 Specifications,21.5 - 37.0 lacs,Hatchback,998 cc,Manual & Automatic,5 - Persons,0
29,Honda Civic 2024 Specifications,83.3 - 99.0 lacs,Sedan,1498 cc,Automatic,5 - Persons,0
30,Honda City 2024 Specifications,-,Compact sedan,1199 - 1497 cc,Manual & Automatic,5 - Persons,0
31,Suzuki Alto 2024 Specifications,23.3 - 30.5 lacs,Hatchback,658 cc,Manual & Automatic,4 - Persons,0
32,Toyota Corolla 2024 Specifications,42.0 lacs,Sedan,1298 - 1800 cc,Manual & Automatic,5 - Persons,0

In [33]:
def adjust_price(price_str):
    try:
        # Remove the 'lacs' and 'crore' text and convert to float
        price_str = price_str.replace('lacs', '').replace('crore', '')
        
        # Split the price range and take the average if it's a range
        prices = price_str.split('-')
        prices = [float(p.strip()) for p in prices if p.strip()]
        avg_price = sum(prices) / len(prices)
        
        # Convert all prices to lacs (1 crore = 100 lacs)
        if 'crore' in price_str:
            avg_price *= 100

        return avg_price
    except:
        return None  # Return None if conversion fails

# Apply the function to the Price column
data['Price'] = data['Price'].apply(adjust_price)

# Show the updated DataFrame
data.head()

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,JW Forland Safari 2024 Specifications,39.000,MPV,1480 cc,Manual,7 - Persons,0
1,MG ZS EV 2024 Specifications,1.400,Compact SUV,-,Automatic,5 - Persons,0
2,MG 4 2024 Specifications,1.200,Crossover,-,Automatic,5 - Persons,0
3,Hyundai Santa Fe 2024 Specifications,1.385,SUV,1598 cc,Automatic,7 - Persons,0
4,GUGO GIGI 2024 Specifications,46.500,Hatchback,-,Automatic,4 - Persons,0

In [34]:
# Multiply all the prices by 100,000 to convert lacs into the actual monetary value
data['Price'] = data['Price'] * 100000

# Show the updated DataFrame
data.head()

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,JW Forland Safari 2024 Specifications,3900000.0,MPV,1480 cc,Manual,7 - Persons,0
1,MG ZS EV 2024 Specifications,140000.0,Compact SUV,-,Automatic,5 - Persons,0
2,MG 4 2024 Specifications,120000.0,Crossover,-,Automatic,5 - Persons,0
3,Hyundai Santa Fe 2024 Specifications,138500.0,SUV,1598 cc,Automatic,7 - Persons,0
4,GUGO GIGI 2024 Specifications,4650000.0,Hatchback,-,Automatic,4 - Persons,0

In [35]:
data

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,JW Forland Safari 2024 Specifications,3900000.0,MPV,1480 cc,Manual,7 - Persons,0
1,MG ZS EV 2024 Specifications,140000.0,Compact SUV,-,Automatic,5 - Persons,0
2,MG 4 2024 Specifications,120000.0,Crossover,-,Automatic,5 - Persons,0
3,Hyundai Santa Fe 2024 Specifications,138500.0,SUV,1598 cc,Automatic,7 - Persons,0
4,GUGO GIGI 2024 Specifications,4650000.0,Hatchback,-,Automatic,4 - Persons,0
5,Seres 3 2024 Specifications,8390000.0,SUV,-,Automatic,5 - Persons,0
6,MG 5 EV 2024 Specifications,135000.0,Station Wagon,-,Automatic,5 - Persons,0
7,Toyota Corolla Cross 2024 Specifications,9025000.0,SUV,1798 cc,Automatic,5 - Persons,0
8,ORA 03 2024 Specifications,9000000.0,Hatchback,-,Automatic,5 - Persons,0
9,Tank 500 2024 Specifications,450000.0,SUV,1998 cc,Automatic,7 - Persons,0
10,Hyundai Ioniq 6 2024 Specifications,230000.0,Compact sedan,-,Automatic,5 - Persons,0
11,Hyundai Ioniq 5 2024 Specifications,225000.0,SUV,-,Automatic,5 - Persons,0
12,Toyota Prado 2024 Specifications,NaN,SUV,2755 cc,Automatic,7 - Persons,0
13,Changan Karvaan 2024 Specifications,2890000.0,Mini Van,999 - 1243 cc,Manual,7 - Persons,0
14,MG HS 2024 Specifications,8250000.0,Crossover,1490 - 1995 cc,Automatic,5 - Persons,0
15,Hyundai Elantra 2024 Specifications,6665000.0,Sedan,1591 - 1999 cc,Automatic,5 - Persons,0
16,Hyundai Tucson 2024 Specifications,7270000.0,SUV,1999 cc,Automatic,5 - Persons,0
17,United Bravo 2024 Specifications,1520000.0,Hatchback,796 cc,Manual,5 - Persons,0
18,Prince Pearl 2024 Specifications,1850000.0,Hatchback,796 cc,Manual & Automatic,5 - Persons,0
19,Toyota Land Cruiser 2024 Specifications,1200000.0,SUV,3444 - 3445 cc,Automatic,7 - Persons,0
20,Changan Alsvin 2024 Specifications,4175000.0,Sedan,1370 - 1480 cc,Manual & Automatic,5 - Persons,0
21,Honda BR-V 2024 Specifications,4375000.0,MPV,1497 cc,Automatic,7 - Persons,0
22,KIA Picanto 2024 Specifications,3725000.0,Hatchback,1000 cc,Manual & Automatic,5 - Persons,0
23,KIA Sportage 2024 Specifications,7350000.0,SUV,1999 cc,Automatic,5 - Persons,0
24,Toyota Fortuner 2024 Specifications,21150000.0,SUV,2694 - 2755 cc,Automatic,7 - Persons,0
25,Suzuki Swift 2024 Specifications,4530000.0,Hatchback,1200 cc,Manual & Automatic,5 - Persons,0
26,Toyota Yaris 2024 Specifications,5090000.0,Sedan,1329 - 1496 cc,Manual & Automatic,5 - Persons,0
27,Suzuki Wagon R 2024 Specifications,1740000.0,Hatchback,998 cc,Manual & Automatic,5 - Persons,0
28,Suzuki Cultus 2024 Specifications,2925000.0,Hatchback,998 cc,Manual & Automatic,5 - Persons,0
29,Honda Civic 2024 Specifications,9115000.0,Sedan,1498 cc,Automatic,5 - Persons,0
30,Honda City 2024 Specifications,NaN,Compact sedan,1199 - 1497 cc,Manual & Automatic,5 - Persons,0
31,Suzuki Alto 2024 Specifications,2690000.0,Hatchback,658 cc,Manual & Automatic,4 - Persons,0
32,Toyota Corolla 2024 Specifications,4200000.0,Sedan,1298 - 1800 cc,Manual & Automatic,5 - Persons,0

In [27]:
data

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,JW Forland Safari 2024 Specifications,3.900000e+06,MPV,1480 cc,Manual,7 - Persons,0
1,MG ZS EV 2024 Specifications,1.400000e+05,Compact SUV,-,Automatic,5 - Persons,0
2,MG 4 2024 Specifications,1.200000e+05,Crossover,-,Automatic,5 - Persons,0
3,Hyundai Santa Fe 2024 Specifications,1.385000e+05,SUV,1598 cc,Automatic,7 - Persons,0
4,GUGO GIGI 2024 Specifications,4.650000e+06,Hatchback,-,Automatic,4 - Persons,0
5,Seres 3 2024 Specifications,8.390000e+06,SUV,-,Automatic,5 - Persons,0
6,MG 5 EV 2024 Specifications,1.350000e+05,Station Wagon,-,Automatic,5 - Persons,0
7,Toyota Corolla Cross 2024 Specifications,9.025000e+06,SUV,1798 cc,Automatic,5 - Persons,0
8,ORA 03 2024 Specifications,9.000000e+06,Hatchback,-,Automatic,5 - Persons,0
9,Tank 500 2024 Specifications,4.500000e+05,SUV,1998 cc,Automatic,7 - Persons,0
10,Hyundai Ioniq 6 2024 Specifications,2.300000e+05,Compact sedan,-,Automatic,5 - Persons,0
11,Hyundai Ioniq 5 2024 Specifications,2.250000e+05,SUV,-,Automatic,5 - Persons,0
12,Toyota Prado 2024 Specifications,4.423016e+06,SUV,2755 cc,Automatic,7 - Persons,0
13,Changan Karvaan 2024 Specifications,2.890000e+06,Mini Van,999 - 1243 cc,Manual,7 - Persons,0
14,MG HS 2024 Specifications,8.250000e+06,Crossover,1490 - 1995 cc,Automatic,5 - Persons,0
15,Hyundai Elantra 2024 Specifications,6.665000e+06,Sedan,1591 - 1999 cc,Automatic,5 - Persons,0
16,Hyundai Tucson 2024 Specifications,7.270000e+06,SUV,1999 cc,Automatic,5 - Persons,0
17,United Bravo 2024 Specifications,1.520000e+06,Hatchback,796 cc,Manual,5 - Persons,0
18,Prince Pearl 2024 Specifications,1.850000e+06,Hatchback,796 cc,Manual & Automatic,5 - Persons,0
19,Toyota Land Cruiser 2024 Specifications,1.200000e+06,SUV,3444 - 3445 cc,Automatic,7 - Persons,0
20,Changan Alsvin 2024 Specifications,4.175000e+06,Sedan,1370 - 1480 cc,Manual & Automatic,5 - Persons,0
21,Honda BR-V 2024 Specifications,4.375000e+06,MPV,1497 cc,Automatic,7 - Persons,0
22,KIA Picanto 2024 Specifications,3.725000e+06,Hatchback,1000 cc,Manual & Automatic,5 - Persons,0
23,KIA Sportage 2024 Specifications,7.350000e+06,SUV,1999 cc,Automatic,5 - Persons,0
24,Toyota Fortuner 2024 Specifications,2.115000e+07,SUV,2694 - 2755 cc,Automatic,7 - Persons,0
25,Suzuki Swift 2024 Specifications,4.530000e+06,Hatchback,1200 cc,Manual & Automatic,5 - Persons,0
26,Toyota Yaris 2024 Specifications,5.090000e+06,Sedan,1329 - 1496 cc,Manual & Automatic,5 - Persons,0
27,Suzuki Wagon R 2024 Specifications,1.740000e+06,Hatchback,998 cc,Manual & Automatic,5 - Persons,0
28,Suzuki Cultus 2024 Specifications,2.925000e+06,Hatchback,998 cc,Manual & Automatic,5 - Persons,0
29,Honda Civic 2024 Specifications,9.115000e+06,Sedan,1498 cc,Automatic,5 - Persons,0
30,Honda City 2024 Specifications,4.423016e+06,Compact sedan,1199 - 1497 cc,Manual & Automatic,5 - Persons,0
31,Suzuki Alto 2024 Specifications,2.690000e+06,Hatchback,658 cc,Manual & Automatic,4 - Persons,0
32,Toyota Corolla 2024 Specifications,4.200000e+06,Sedan,1298 - 1800 cc,Manual & Automatic,5 - Persons,0

In [36]:
data

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,JW Forland Safari 2024 Specifications,3900000.0,MPV,1480 cc,Manual,7 - Persons,0
1,MG ZS EV 2024 Specifications,140000.0,Compact SUV,-,Automatic,5 - Persons,0
2,MG 4 2024 Specifications,120000.0,Crossover,-,Automatic,5 - Persons,0
3,Hyundai Santa Fe 2024 Specifications,138500.0,SUV,1598 cc,Automatic,7 - Persons,0
4,GUGO GIGI 2024 Specifications,4650000.0,Hatchback,-,Automatic,4 - Persons,0
5,Seres 3 2024 Specifications,8390000.0,SUV,-,Automatic,5 - Persons,0
6,MG 5 EV 2024 Specifications,135000.0,Station Wagon,-,Automatic,5 - Persons,0
7,Toyota Corolla Cross 2024 Specifications,9025000.0,SUV,1798 cc,Automatic,5 - Persons,0
8,ORA 03 2024 Specifications,9000000.0,Hatchback,-,Automatic,5 - Persons,0
9,Tank 500 2024 Specifications,450000.0,SUV,1998 cc,Automatic,7 - Persons,0
10,Hyundai Ioniq 6 2024 Specifications,230000.0,Compact sedan,-,Automatic,5 - Persons,0
11,Hyundai Ioniq 5 2024 Specifications,225000.0,SUV,-,Automatic,5 - Persons,0
12,Toyota Prado 2024 Specifications,NaN,SUV,2755 cc,Automatic,7 - Persons,0
13,Changan Karvaan 2024 Specifications,2890000.0,Mini Van,999 - 1243 cc,Manual,7 - Persons,0
14,MG HS 2024 Specifications,8250000.0,Crossover,1490 - 1995 cc,Automatic,5 - Persons,0
15,Hyundai Elantra 2024 Specifications,6665000.0,Sedan,1591 - 1999 cc,Automatic,5 - Persons,0
16,Hyundai Tucson 2024 Specifications,7270000.0,SUV,1999 cc,Automatic,5 - Persons,0
17,United Bravo 2024 Specifications,1520000.0,Hatchback,796 cc,Manual,5 - Persons,0
18,Prince Pearl 2024 Specifications,1850000.0,Hatchback,796 cc,Manual & Automatic,5 - Persons,0
19,Toyota Land Cruiser 2024 Specifications,1200000.0,SUV,3444 - 3445 cc,Automatic,7 - Persons,0
20,Changan Alsvin 2024 Specifications,4175000.0,Sedan,1370 - 1480 cc,Manual & Automatic,5 - Persons,0
21,Honda BR-V 2024 Specifications,4375000.0,MPV,1497 cc,Automatic,7 - Persons,0
22,KIA Picanto 2024 Specifications,3725000.0,Hatchback,1000 cc,Manual & Automatic,5 - Persons,0
23,KIA Sportage 2024 Specifications,7350000.0,SUV,1999 cc,Automatic,5 - Persons,0
24,Toyota Fortuner 2024 Specifications,21150000.0,SUV,2694 - 2755 cc,Automatic,7 - Persons,0
25,Suzuki Swift 2024 Specifications,4530000.0,Hatchback,1200 cc,Manual & Automatic,5 - Persons,0
26,Toyota Yaris 2024 Specifications,5090000.0,Sedan,1329 - 1496 cc,Manual & Automatic,5 - Persons,0
27,Suzuki Wagon R 2024 Specifications,1740000.0,Hatchback,998 cc,Manual & Automatic,5 - Persons,0
28,Suzuki Cultus 2024 Specifications,2925000.0,Hatchback,998 cc,Manual & Automatic,5 - Persons,0
29,Honda Civic 2024 Specifications,9115000.0,Sedan,1498 cc,Automatic,5 - Persons,0
30,Honda City 2024 Specifications,NaN,Compact sedan,1199 - 1497 cc,Manual & Automatic,5 - Persons,0
31,Suzuki Alto 2024 Specifications,2690000.0,Hatchback,658 cc,Manual & Automatic,4 - Persons,0
32,Toyota Corolla 2024 Specifications,4200000.0,Sedan,1298 - 1800 cc,Manual & Automatic,5 - Persons,0

In [37]:
import numpy as np

In [39]:
import pandas as pd
import numpy as np

# Load the data

# Function to clean the displacement values
def clean_displacement(value):
    if isinstance(value, str):
        value = value.replace('cc', '').strip()
        if '-' in value:
            values = value.split('-')
            return np.mean([float(v.strip()) for v in values if v.strip()])
        elif value.isdigit():
            return float(value)
    return np.nan

# Apply the function to clean up the displacement
data['Displacement'] = data['Displacement'].apply(clean_displacement)

# Calculate the mean displacement, ignoring NaNs
mean_displacement = data['Displacement'].mean()

# Replace NaN values with the mean displacement
data['Displacement'].fillna(mean_displacement, inplace=True)

# Save the cleaned data to a new CSV file
data.to_csv('cleaned_data.csv', index=False)

# Display the updated DataFrame
print(data.head())

                                     Name      Price    Body Type  \
0  JW Forland Safari  2024 Specifications  3900000.0          MPV
1            MG ZS EV 2024 Specifications   140000.0  Compact SUV
2                MG 4 2024 Specifications   120000.0    Crossover
3    Hyundai Santa Fe 2024 Specifications   138500.0          SUV
4           GUGO GIGI 2024 Specifications  4650000.0    Hatchback

   Displacement Transmission Seating Capacity  Odometer
0        1480.0       Manual      7 - Persons         0
1        1585.2    Automatic      5 - Persons         0
2        1585.2    Automatic      5 - Persons         0
3        1598.0    Automatic      7 - Persons         0
4        1585.2    Automatic      4 - Persons         0

/Users/aawaizali/Library/Mobile Documents/com~apple~CloudDocs/Code/pynb/practice/Car-Price-Prediction-Model/env/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/aawaizali/Library/Mobile Documents/com~apple~CloudDocs/Code/pynb/practice/Car-Price-Prediction-Model/env/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/var/folders/qq/825c9lpx42x0rhxk9smb4c8h0000gq/T/ipykernel_15394/3916558512.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Displacement'].fillna(mean_displacement, inplace=True)

In [40]:
data

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,JW Forland Safari 2024 Specifications,3900000.0,MPV,1480.0,Manual,7 - Persons,0
1,MG ZS EV 2024 Specifications,140000.0,Compact SUV,1585.2,Automatic,5 - Persons,0
2,MG 4 2024 Specifications,120000.0,Crossover,1585.2,Automatic,5 - Persons,0
3,Hyundai Santa Fe 2024 Specifications,138500.0,SUV,1598.0,Automatic,7 - Persons,0
4,GUGO GIGI 2024 Specifications,4650000.0,Hatchback,1585.2,Automatic,4 - Persons,0
5,Seres 3 2024 Specifications,8390000.0,SUV,1585.2,Automatic,5 - Persons,0
6,MG 5 EV 2024 Specifications,135000.0,Station Wagon,1585.2,Automatic,5 - Persons,0
7,Toyota Corolla Cross 2024 Specifications,9025000.0,SUV,1798.0,Automatic,5 - Persons,0
8,ORA 03 2024 Specifications,9000000.0,Hatchback,1585.2,Automatic,5 - Persons,0
9,Tank 500 2024 Specifications,450000.0,SUV,1998.0,Automatic,7 - Persons,0
10,Hyundai Ioniq 6 2024 Specifications,230000.0,Compact sedan,1585.2,Automatic,5 - Persons,0
11,Hyundai Ioniq 5 2024 Specifications,225000.0,SUV,1585.2,Automatic,5 - Persons,0
12,Toyota Prado 2024 Specifications,NaN,SUV,2755.0,Automatic,7 - Persons,0
13,Changan Karvaan 2024 Specifications,2890000.0,Mini Van,1121.0,Manual,7 - Persons,0
14,MG HS 2024 Specifications,8250000.0,Crossover,1742.5,Automatic,5 - Persons,0
15,Hyundai Elantra 2024 Specifications,6665000.0,Sedan,1795.0,Automatic,5 - Persons,0
16,Hyundai Tucson 2024 Specifications,7270000.0,SUV,1999.0,Automatic,5 - Persons,0
17,United Bravo 2024 Specifications,1520000.0,Hatchback,796.0,Manual,5 - Persons,0
18,Prince Pearl 2024 Specifications,1850000.0,Hatchback,796.0,Manual & Automatic,5 - Persons,0
19,Toyota Land Cruiser 2024 Specifications,1200000.0,SUV,3444.5,Automatic,7 - Persons,0
20,Changan Alsvin 2024 Specifications,4175000.0,Sedan,1425.0,Manual & Automatic,5 - Persons,0
21,Honda BR-V 2024 Specifications,4375000.0,MPV,1497.0,Automatic,7 - Persons,0
22,KIA Picanto 2024 Specifications,3725000.0,Hatchback,1000.0,Manual & Automatic,5 - Persons,0
23,KIA Sportage 2024 Specifications,7350000.0,SUV,1999.0,Automatic,5 - Persons,0
24,Toyota Fortuner 2024 Specifications,21150000.0,SUV,2724.5,Automatic,7 - Persons,0
25,Suzuki Swift 2024 Specifications,4530000.0,Hatchback,1200.0,Manual & Automatic,5 - Persons,0
26,Toyota Yaris 2024 Specifications,5090000.0,Sedan,1412.5,Manual & Automatic,5 - Persons,0
27,Suzuki Wagon R 2024 Specifications,1740000.0,Hatchback,998.0,Manual & Automatic,5 - Persons,0
28,Suzuki Cultus 2024 Specifications,2925000.0,Hatchback,998.0,Manual & Automatic,5 - Persons,0
29,Honda Civic 2024 Specifications,9115000.0,Sedan,1498.0,Automatic,5 - Persons,0
30,Honda City 2024 Specifications,NaN,Compact sedan,1348.0,Manual & Automatic,5 - Persons,0
31,Suzuki Alto 2024 Specifications,2690000.0,Hatchback,658.0,Manual & Automatic,4 - Persons,0
32,Toyota Corolla 2024 Specifications,4200000.0,Sedan,1549.0,Manual & Automatic,5 - Persons,0

In [42]:
def clean_seating_capacity(value):
    if isinstance(value, str):
        # Remove the word 'Person' and any potential plurals
        value = value.replace('Persons', '').replace('Person', '').strip()
        # Handle ranges by taking the maximum value
        if '-' in value:
            return max([int(v.strip()) for v in value.split('-')])
        return int(value)
    return None  # Return None for unexpected data types

# Apply the function to clean up the seating capacity
data['Seating Capacity'] = data['Seating Capacity'].apply(clean_seating_capacity)

# Save the cleaned data to a new CSV file

# Display the updated DataFrame
print(data.head())

ValueError: invalid literal for int() with base 10: ''

In [43]:
def clean_seating_capacity(value):
    if isinstance(value, str):
        # Remove the word 'Persons' or 'Person' and any spaces
        value = value.replace('Persons', '').replace('Person', '').strip()
        # If the value is a range, take the maximum value
        if '-' in value:
            values = [int(v.strip()) for v in value.split('-') if v.strip().isdigit()]
            return max(values) if values else None
        elif value.isdigit():
            return int(value)
    return None  # Handle cases where conversion is not possible

# Apply the function to clean up the seating capacity
data['Seating Capacity'] = data['Seating Capacity'].apply(clean_seating_capacity)

# Save the cleaned data to a new CSV file

# Display the updated DataFrame
print(data.head())

                                     Name      Price    Body Type  \
0  JW Forland Safari  2024 Specifications  3900000.0          MPV
1            MG ZS EV 2024 Specifications   140000.0  Compact SUV
2                MG 4 2024 Specifications   120000.0    Crossover
3    Hyundai Santa Fe 2024 Specifications   138500.0          SUV
4           GUGO GIGI 2024 Specifications  4650000.0    Hatchback

   Displacement Transmission  Seating Capacity  Odometer
0        1480.0       Manual                 7         0
1        1585.2    Automatic                 5         0
2        1585.2    Automatic                 5         0
3        1598.0    Automatic                 7         0
4        1585.2    Automatic                 4         0

In [44]:
data

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,JW Forland Safari 2024 Specifications,3900000.0,MPV,1480.0,Manual,7,0
1,MG ZS EV 2024 Specifications,140000.0,Compact SUV,1585.2,Automatic,5,0
2,MG 4 2024 Specifications,120000.0,Crossover,1585.2,Automatic,5,0
3,Hyundai Santa Fe 2024 Specifications,138500.0,SUV,1598.0,Automatic,7,0
4,GUGO GIGI 2024 Specifications,4650000.0,Hatchback,1585.2,Automatic,4,0
5,Seres 3 2024 Specifications,8390000.0,SUV,1585.2,Automatic,5,0
6,MG 5 EV 2024 Specifications,135000.0,Station Wagon,1585.2,Automatic,5,0
7,Toyota Corolla Cross 2024 Specifications,9025000.0,SUV,1798.0,Automatic,5,0
8,ORA 03 2024 Specifications,9000000.0,Hatchback,1585.2,Automatic,5,0
9,Tank 500 2024 Specifications,450000.0,SUV,1998.0,Automatic,7,0
10,Hyundai Ioniq 6 2024 Specifications,230000.0,Compact sedan,1585.2,Automatic,5,0
11,Hyundai Ioniq 5 2024 Specifications,225000.0,SUV,1585.2,Automatic,5,0
12,Toyota Prado 2024 Specifications,NaN,SUV,2755.0,Automatic,7,0
13,Changan Karvaan 2024 Specifications,2890000.0,Mini Van,1121.0,Manual,7,0
14,MG HS 2024 Specifications,8250000.0,Crossover,1742.5,Automatic,5,0
15,Hyundai Elantra 2024 Specifications,6665000.0,Sedan,1795.0,Automatic,5,0
16,Hyundai Tucson 2024 Specifications,7270000.0,SUV,1999.0,Automatic,5,0
17,United Bravo 2024 Specifications,1520000.0,Hatchback,796.0,Manual,5,0
18,Prince Pearl 2024 Specifications,1850000.0,Hatchback,796.0,Manual & Automatic,5,0
19,Toyota Land Cruiser 2024 Specifications,1200000.0,SUV,3444.5,Automatic,7,0
20,Changan Alsvin 2024 Specifications,4175000.0,Sedan,1425.0,Manual & Automatic,5,0
21,Honda BR-V 2024 Specifications,4375000.0,MPV,1497.0,Automatic,7,0
22,KIA Picanto 2024 Specifications,3725000.0,Hatchback,1000.0,Manual & Automatic,5,0
23,KIA Sportage 2024 Specifications,7350000.0,SUV,1999.0,Automatic,5,0
24,Toyota Fortuner 2024 Specifications,21150000.0,SUV,2724.5,Automatic,7,0
25,Suzuki Swift 2024 Specifications,4530000.0,Hatchback,1200.0,Manual & Automatic,5,0
26,Toyota Yaris 2024 Specifications,5090000.0,Sedan,1412.5,Manual & Automatic,5,0
27,Suzuki Wagon R 2024 Specifications,1740000.0,Hatchback,998.0,Manual & Automatic,5,0
28,Suzuki Cultus 2024 Specifications,2925000.0,Hatchback,998.0,Manual & Automatic,5,0
29,Honda Civic 2024 Specifications,9115000.0,Sedan,1498.0,Automatic,5,0
30,Honda City 2024 Specifications,NaN,Compact sedan,1348.0,Manual & Automatic,5,0
31,Suzuki Alto 2024 Specifications,2690000.0,Hatchback,658.0,Manual & Automatic,4,0
32,Toyota Corolla 2024 Specifications,4200000.0,Sedan,1549.0,Manual & Automatic,5,0

In [45]:
data = data.dropna(subset=['Price'])

In [46]:
data

,Name,Price,Body Type,Displacement,Transmission,Seating Capacity,Odometer
0,JW Forland Safari 2024 Specifications,3900000.0,MPV,1480.0,Manual,7,0
1,MG ZS EV 2024 Specifications,140000.0,Compact SUV,1585.2,Automatic,5,0
2,MG 4 2024 Specifications,120000.0,Crossover,1585.2,Automatic,5,0
3,Hyundai Santa Fe 2024 Specifications,138500.0,SUV,1598.0,Automatic,7,0
4,GUGO GIGI 2024 Specifications,4650000.0,Hatchback,1585.2,Automatic,4,0
5,Seres 3 2024 Specifications,8390000.0,SUV,1585.2,Automatic,5,0
6,MG 5 EV 2024 Specifications,135000.0,Station Wagon,1585.2,Automatic,5,0
7,Toyota Corolla Cross 2024 Specifications,9025000.0,SUV,1798.0,Automatic,5,0
8,ORA 03 2024 Specifications,9000000.0,Hatchback,1585.2,Automatic,5,0
9,Tank 500 2024 Specifications,450000.0,SUV,1998.0,Automatic,7,0
10,Hyundai Ioniq 6 2024 Specifications,230000.0,Compact sedan,1585.2,Automatic,5,0
11,Hyundai Ioniq 5 2024 Specifications,225000.0,SUV,1585.2,Automatic,5,0
13,Changan Karvaan 2024 Specifications,2890000.0,Mini Van,1121.0,Manual,7,0
14,MG HS 2024 Specifications,8250000.0,Crossover,1742.5,Automatic,5,0
15,Hyundai Elantra 2024 Specifications,6665000.0,Sedan,1795.0,Automatic,5,0
16,Hyundai Tucson 2024 Specifications,7270000.0,SUV,1999.0,Automatic,5,0
17,United Bravo 2024 Specifications,1520000.0,Hatchback,796.0,Manual,5,0
18,Prince Pearl 2024 Specifications,1850000.0,Hatchback,796.0,Manual & Automatic,5,0
19,Toyota Land Cruiser 2024 Specifications,1200000.0,SUV,3444.5,Automatic,7,0
20,Changan Alsvin 2024 Specifications,4175000.0,Sedan,1425.0,Manual & Automatic,5,0
21,Honda BR-V 2024 Specifications,4375000.0,MPV,1497.0,Automatic,7,0
22,KIA Picanto 2024 Specifications,3725000.0,Hatchback,1000.0,Manual & Automatic,5,0
23,KIA Sportage 2024 Specifications,7350000.0,SUV,1999.0,Automatic,5,0
24,Toyota Fortuner 2024 Specifications,21150000.0,SUV,2724.5,Automatic,7,0
25,Suzuki Swift 2024 Specifications,4530000.0,Hatchback,1200.0,Manual & Automatic,5,0
26,Toyota Yaris 2024 Specifications,5090000.0,Sedan,1412.5,Manual & Automatic,5,0
27,Suzuki Wagon R 2024 Specifications,1740000.0,Hatchback,998.0,Manual & Automatic,5,0
28,Suzuki Cultus 2024 Specifications,2925000.0,Hatchback,998.0,Manual & Automatic,5,0
29,Honda Civic 2024 Specifications,9115000.0,Sedan,1498.0,Automatic,5,0
31,Suzuki Alto 2024 Specifications,2690000.0,Hatchback,658.0,Manual & Automatic,4,0
32,Toyota Corolla 2024 Specifications,4200000.0,Sedan,1549.0,Manual & Automatic,5,0

In [48]:
data.to_csv('ready_new.csv')